

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gumi_chelin?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssafy
    password: ssafy

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.ssafy.gumichelin.model.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.ssafy.gumichelin : info
